/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import controller.Manager;
import exceptions.ManagerException;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.score.Score;
import model.user.User;

/**
 *
 * @author Yuli
 */
public class DeleteUser extends javax.swing.JDialog {

    /**
     * Creates new form DeleteUser
     */
    public DeleteUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Manager.getManager().setIcon(this, null);
        Manager.getManager().generateSelect(userSelected, "user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserdelete = new javax.swing.JLabel();
        userSelected = new javax.swing.JComboBox<>();
        deleteUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete User");

        labelUserdelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUserdelete.setText("Choose a user");

        deleteUserButton.setText("Delete");
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserButtonMouseClicked(evt);
            }
        });
        deleteUserButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteUserButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUserdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(userSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserButtonMouseClicked
        delete();
    }//GEN-LAST:event_deleteUserButtonMouseClicked

    private void deleteUserButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteUserButtonKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            delete();
        }
    }//GEN-LAST:event_deleteUserButtonKeyPressed

       private void delete() {
        if (userSelected.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "User not selected", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            int optionSelected = JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete User", JOptionPane.YES_NO_CANCEL_OPTION);
            // 0=yes, 1=no, 2=cancel
            if (optionSelected == 0) {
                try {
                    String nameUser = userSelected.getSelectedItem().toString();
                    User userForDelete = Manager.getManager().checkExistUser(nameUser);
                    if (userForDelete == null) {
                        JOptionPane.showMessageDialog(this, "User not registred", "Message", JOptionPane.WARNING_MESSAGE);
                    } else {
                        if (Manager.getManager().deleteUser(userForDelete)) {
                            JOptionPane.showMessageDialog(this, "User deleted successful", "Message", JOptionPane.INFORMATION_MESSAGE);
                            userSelected.removeAllItems();
                            Manager.getManager().generateSelect(userSelected, "user");
                        } else {
                            JOptionPane.showMessageDialog(this, "hola", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }

                } catch (ManagerException ex) {
                    JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel labelUserdelete;
    private javax.swing.JComboBox<String> userSelected;
    // End of variables declaration//GEN-END:variables
}
