/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import SwingTools.SwingTools;
import controller.Manager;
import exceptions.InputOutputException;
import exceptions.ManagerException;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import model.score.Score;

/**
 *
 * @author Yuli
 */
public class ModifyScore extends javax.swing.JDialog {

    /**
     * Creates new form ModifyScore
     */
    public ModifyScore(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SwingTools.getSwingTools().setIcon(this, null);
        modifyButton.setEnabled(false);
        TreeMap<String, Score> userScores = Manager.getManager().getCurrentUser().getScores();
        for (Map.Entry<String, Score> codeScoreItem : userScores.entrySet()) {
            scoreSelected.addItem(codeScoreItem.getKey());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyLevel = new javax.swing.ButtonGroup();
        labelForChooseScore = new javax.swing.JLabel();
        scoreSelected = new javax.swing.JComboBox<>();
        datos = new javax.swing.JPanel();
        codeLabel = new javax.swing.JLabel();
        codeScoreSelected = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        artistLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        instrumentLabel = new javax.swing.JLabel();
        printedLabel = new javax.swing.JLabel();
        titleScoreSelected = new javax.swing.JTextField();
        artistScoreSeleted = new javax.swing.JTextField();
        isPrintedSelected = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        genreScoreSelected = new javax.swing.JTextField();
        difficultyLevelLabel = new javax.swing.JLabel();
        instrumentScoreSelected = new javax.swing.JComboBox<>();
        selectScore = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Score");

        labelForChooseScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelForChooseScore.setText("Choose a score");

        codeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codeLabel.setText("Code");

        codeScoreSelected.setEditable(false);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("Title");

        artistLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        artistLabel.setText("Artist");

        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderLabel.setText("Genre");

        instrumentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instrumentLabel.setText("Instrument");

        printedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printedLabel.setText("Printed");

        titleScoreSelected.setEditable(false);

        artistScoreSeleted.setEditable(false);

        difficultyLevel.add(jRadioButton1);
        jRadioButton1.setText("low");

        difficultyLevel.add(jRadioButton2);
        jRadioButton2.setText("medium");

        difficultyLevel.add(jRadioButton3);
        jRadioButton3.setText("high");

        genreScoreSelected.setEditable(false);

        difficultyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        difficultyLevelLabel.setText("Difficulty level");

        instrumentScoreSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Battery", "Flute", "Guitar", "Bass Guitar", "Piano" }));

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficultyLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(instrumentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artistLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codeScoreSelected)
                            .addComponent(titleScoreSelected)
                            .addComponent(artistScoreSeleted)
                            .addComponent(genreScoreSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(instrumentScoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(268, 268, 268))
            .addGroup(datosLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(printedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(isPrintedSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeScoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleScoreSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistScoreSeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreScoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(instrumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosLayout.createSequentialGroup()
                        .addComponent(instrumentScoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(difficultyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3)))
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isPrintedSelected, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        selectScore.setText("Select");
        selectScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectScoreActionPerformed(evt);
            }
        });

        modifyButton.setText("Modify");
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelForChooseScore, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(scoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectScore, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForChooseScore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectScore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectScoreActionPerformed
        if (scoreSelected.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Score not selected", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            modifyButton.setEnabled(true);
            String codeScoreSelected = scoreSelected.getSelectedItem().toString();
            try {
                Score scoreForModify = Manager.getManager().checkExistUserScore(codeScoreSelected);
                this.codeScoreSelected.setText(scoreForModify.getCode());
                titleScoreSelected.setText(scoreForModify.getTitle());
                artistScoreSeleted.setText(scoreForModify.getArtist());
                genreScoreSelected.setText(scoreForModify.getGenre());
                for (int i = 0; i < instrumentScoreSelected.getItemCount(); i++) {
                    if (instrumentScoreSelected.getItemAt(i).equals(scoreForModify.getInstrument())) {
                        instrumentScoreSelected.setSelectedIndex(i);
                    }
                }
                SwingTools.getSwingTools().setSelectedButtonText(scoreForModify.getDifficultyLevel(), difficultyLevel);
                isPrintedSelected.setSelected(scoreForModify.isIsPrinted());
            } catch (ManagerException ex) {
                JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_selectScoreActionPerformed

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        String code = codeScoreSelected.getText();
        String title = titleScoreSelected.getText();
        String artist = artistScoreSeleted.getText();
        String genre = genreScoreSelected.getText();
        String instrumentScore = instrumentScoreSelected.getSelectedItem().toString();
        String difficultyLevelScore = SwingTools.getSwingTools().getSelectedButtonText(difficultyLevel);
        boolean isPrintedScore = isPrintedSelected.isSelected();
        try {
            if (Manager.getManager().modifyScore(code, title, artist, instrumentScore, genre, difficultyLevelScore, isPrintedScore)) {
                JOptionPane.showMessageDialog(this, "Score modified successful", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "It has not been possible to modify score ", "Message", JOptionPane.WARNING_MESSAGE);
            }
        } catch (InputOutputException ex) {
            JOptionPane.showMessageDialog(this, "" + ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_modifyButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artistLabel;
    private javax.swing.JTextField artistScoreSeleted;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeScoreSelected;
    private javax.swing.JPanel datos;
    private javax.swing.ButtonGroup difficultyLevel;
    private javax.swing.JLabel difficultyLevelLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genreScoreSelected;
    private javax.swing.JLabel instrumentLabel;
    private javax.swing.JComboBox<String> instrumentScoreSelected;
    private javax.swing.JCheckBox isPrintedSelected;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel labelForChooseScore;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel printedLabel;
    private javax.swing.JComboBox<String> scoreSelected;
    private javax.swing.JButton selectScore;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleScoreSelected;
    // End of variables declaration//GEN-END:variables
}
